### ISSUE TITLE
Cleanup command from Dotbot

### ISSUE THREAD

**Issue by tofagerl** [vulpino/dit#3]
I like this project a whole lot better than Dotbot, and have already switched to it. However, there is one thing I miss from Dotbot, and that is the cleanup of dead links. Before Dotbot starts it's symlinking, it removes all dead links and then checks all the existing links before it makes new symlinks for the dotfiles. 

In other words, whereas the result from Dotbot's process is a correct set of symlinks for all dotfiles, the result from Dit's process could be dead links for files that used to exist but doesn't anymore, and a lot of "Failed to symlink" errors. 

This is annoying and possibly a huge problem if you (like me) have sets of interdependent dotfiles for eg. zsh, vim or even tmux.

**Comment by fluffgfx** [comment]
I can definitely implement that. I'll work on that for 0.3

**Comment by tofagerl** [comment]
Great, thanks! Love the simplicity of this system. No config files, no manuals. Four possible commands. 

Oh, and perhaps add a uninstall command to remove the symlinks at the same time. I've needed that a couple times when making large changes.

**Comment by fluffgfx** [comment]
Hey, I've just added a `dit clean` command. Its operation is fairly simple -
1. Run `dit clean` to move all existing dotfiles with a .old suffix - e.g. `.vimrc` to `.vimrc.old` - and delete all dead symlinks.
2. Run `dit clean --destructive` (or `dit clean -d`) to delete all existing dotfiles - this will delete everything that isn't symlinked to the working directory, so use with caution.
Any other questions or options needed? I'll have this in the 0.3 version of the gem, which I plan to have out by Friday.

**Comment by tofagerl** [comment]
Sounds good :+1:
