### ISSUE TITLE
Auto-creation of dotfile folders

### ISSUE THREAD

**Issue by marplesoft** [vulpino/dit#4]
In addition to dotfiles themselves it's common to have folders that contain dotfile-like files. For example I have a `.hammerspoon` directory with has lua files in it that I'd like to sync. Maybe `.vim` too? 

This _almost_ works right now except it doesn't auto-create those directories so the symlink creation fails because it's trying to create the link in a folder that doesn't exist.

What do you think about making the following addition?

``` ruby
 def self.symlink_list(list)
   list.each do |f|
     f.strip!
     wd_f = File.absolute_path f
     home_f = File.absolute_path(f).gsub(Dir.getwd, Dir.home)
+    home_dir_f = File.dirname(home_f)
+    FileUtils.mkdir_p(home_dir_f)
     symlink wd_f, home_f
   end 
end
```

Alternatively, maybe it should symlink the folder itself? In that case you'd have to change how you get the file list using `git ls-tree`.

**Comment by fluffgfx** [comment]
Thanks, I'll patch this in for 0.3

**Comment by marplesoft** [comment]
K, but the more I think about it, it should probably be the folder that's symlinked, no? So this patch above wouldn't be the right approach. Instead it would need to list top-level files and folders from the working dir and link those I suppose?

**Comment by fluffgfx** [comment]
You're right, and I think I've got an approach which does as such

``` ruby
def self.symlink_all
  current_branch = `git rev-parse --abbrev-ref HEAD`.chomp
  file_list = `git ls-tree -r #{current_branch} --name-only`.split("\n")
  list = []
  file_list.each do |f|
    folder = f.split("/")[0]
    list | [folder]
  end
  symlink_list list
end
```

Alternatively, I think `Dir.glob('*')` would work, but I don't want to symlink elements not checked into git.

**Comment by fluffgfx** [comment]
Here's the implementation:

``` ruby
def self.symlink_list(list)
+    puts list.to_s
+    root_list = Set.new []
     list.each do |f|
         f.strip!
+        root = f.split('/')[0]
+        root ||= f
+        root_list = root_list | Set[root]
+    end
+    puts root_list.to_a.to_s
+    root_list.to_a.each do |f|
       wd_f = File.absolute_path f
       home_f = File.absolute_path(f).gsub(Dir.getwd, Dir.home)
       symlink wd_f, home_f
    end
  end
```

Might be a little lengthy (looks like I forgot to pull the `puts` debugging calls - whoops) but the gist is given this array:
`["", ".vim/.netrwhist", ".vim/bundle/Vundle.vim"]`

The following is symlinked (bar the empty string, which I'll add a check for):
`["", ".vim"]`
