### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by tofagerl** [vulpino/dit#5]
I have some folders in my dotfiles, like .ssh, .tmux, .config and so on. Right now these are ignored, and I have to manually recreate them in $HOME, after which dit works fine. Except of course if there are subdirectories...
Would it be possible to simply create symlinks for the directories as well?

**Comment by fluffgfx** [comment]
Pushed dit 0.3 about ten minutes ago, which fixes the issue. See issue #4 for discussion.

(It should at any rate - do folders still not symlink in 0.3?)

**Comment by tofagerl** [comment]
Okidoki! Seems to work fine, but I don't have a chance to check right now. I rehashed, but a proper test would have to include a fresh install.
Is there any reason to create an issue about the error messages "failed to symlink" when the symlinks are already generated and working just fine? I assume you know about them, but they're only a problem if you're allergic to errors.

**Comment by fluffgfx** [comment]
Yeah, that's something I need to work on. I'll open an issue for that - I have a line that's supposed to prevent attempts to symlink files that are already symlinked to the working directory but it's clearly not working as intended.

``` ruby
return if (File.symlink?(b) && File.readlink(b).include(Dir.getwd))
```
